name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 13.60.157.36
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Devops-demo
            git pull origin main
            npm install
            # 1. Force a fresh build by clearing the old cache
            # 2. Use sudo to avoid the 'Permission Denied' error
            sudo npx expo export --platform web --clear
            # 3. Ensure Nginx has permission to read the newly created files
            sudo chmod -R 755 /home/ubuntu/Devops-demo/dist
            # 4. Restart Nginx to pick up any changes
            sudo systemctl restart nginx